'use client'

import useSWR from 'swr'
import { ArrowUpRight, Check, CircleHelp, Database, ExternalLink, Gauge, LoaderCircle, RefreshCw, ShieldCheck } from 'lucide-react'
import { fetcher, type MarketState } from '@/hooks/use-market'
import type { SourceResult } from '@/lib/market-types'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Panel, DataRow } from './panel'
import { cn } from '@/lib/utils'

export function SourcesPanel({ market: m }: { market: MarketState }) {
  const { data, isLoading, isValidating, error, mutate } = useSWR<{ sources: SourceResult[]; testedAt: number; note: string }>('/api/market/sources', fetcher, { dedupingInterval: 60_000, revalidateOnFocus: false, errorRetryCount: 1 })
  const fastest = data?.sources.filter(s => s.available).sort((a, b) => (a.latency || 0) - (b.latency || 0))[0]?.name
  return <div className="flex flex-col gap-4"><div className="mb-2"><div className="eyebrow">DATA PROVENANCE</div><h2 className="mt-2 text-2xl font-medium tracking-tight">Real markets. Verifiable sources.</h2><p className="mt-2 max-w-2xl text-xs leading-relaxed text-muted-foreground">Every market number comes from the exchange. Source availability and speed are measured from this deployment, not assumed. No tokenized-gold substitutes or simulated prices.</p></div>
    <Panel title="Exchange connectivity benchmark" icon={<Gauge className="size-3.5" />} action={<Button variant="outline" size="xs" onClick={() => void mutate()} disabled={isValidating} className="text-[10px]"><RefreshCw className={cn('size-3!', isValidating && 'animate-spin')} />Retest sources</Button>}>
      <div className="overflow-x-auto"><table className="w-full min-w-150 text-left text-xs"><thead><tr className="border-b border-border text-[10px] text-muted-foreground">{['Exchange', 'Exact instrument', 'Availability', 'Median REST RTT', 'Route'].map(h => <th key={h} className="px-5 py-4 font-normal">{h}</th>)}</tr></thead><tbody>{data?.sources.map(source => <tr key={source.name} className="border-b border-border last:border-0"><td className="px-5 py-5 font-medium">{source.name}</td><td className="px-5 py-5 font-mono text-[11px]">{source.symbol}</td><td className={cn('px-5 py-5 text-[11px]', source.available ? 'text-positive' : 'text-primary')}>{source.status}</td><td className="px-5 py-5 font-mono">{source.latency === null ? '—' : `${source.latency} ms`}{fastest === source.name && <span className="ml-2 text-[9px] text-positive">FASTEST TEST</span>}</td><td className="px-5 py-5">{source.name === 'OKX' ? <Badge variant="outline" className="rounded border-primary/30 text-[9px] text-primary">SELECTED FEED</Badge> : <span className="text-[10px] text-muted-foreground">Benchmark only</span>}</td></tr>)}{!data && <tr><td colSpan={5} className="p-8 text-center text-muted-foreground">{error ? 'Benchmark unavailable. Retry to run a new test.' : <span className="inline-flex items-center gap-2"><LoaderCircle className="size-4 animate-spin" />Testing exact XAU contracts…</span>}</td></tr>}</tbody></table></div>
      <div className="border-t border-border px-5 py-4 text-[10px] leading-relaxed text-muted-foreground">{data?.note || '3 real requests per venue. Region restrictions are respected, not bypassed.'}{data && <div className="mt-1 font-mono">Measured {new Date(data.testedAt).toISOString().replace('T', ' ').slice(0, 19)} UTC</div>}</div>
    </Panel>
    <div className="grid gap-4 md:grid-cols-2"><Panel title="Live feed health" icon={<Database className="size-3.5" />}><div className="divide-y divide-border px-5 py-2"><DataRow label="Primary transport">{m.connected ? 'Public WebSocket' : 'REST recovery · 3s'}</DataRow><DataRow label="Book channel">books5 · full snapshots</DataRow><DataRow label="Exchange quote age">{m.quoteAge === null ? '—' : `${m.quoteAge} ms`}</DataRow><DataRow label="Order book age">{m.bookAge === null ? '—' : `${m.bookAge} ms`}</DataRow><DataRow label="REST batch time">{m.snapshot ? `${m.snapshot.latency} ms` : '—'}</DataRow><DataRow label="Instrument identity">{m.verified ? 'Verified XAU-USDT-SWAP' : 'Not verified'}</DataRow></div></Panel><Panel title="Source & research notes" icon={<CircleHelp className="size-3.5" />}><div className="space-y-4 p-5 text-xs leading-relaxed text-muted-foreground"><p>OKX documents books5 snapshots up to every 100 ms when depth changes. This is publisher cadence, not guaranteed end-to-end latency. Rendering is batched to avoid unnecessary work.</p><p>MEXC or another venue may be faster from this server in a given test. The terminal deliberately stays on OKX so charts, tick sizes and signals never mix different markets.</p><p>Availability is jurisdiction-dependent. If the exact instrument or feed is unavailable, entries are blocked rather than filled with another asset.</p><a className="inline-flex items-center gap-1 text-primary hover:underline" href="https://www.okx.com/docs-v5/en/" target="_blank" rel="noreferrer">Read official OKX API documentation<ExternalLink className="size-3" /></a></div></Panel></div>
  </div>
}
