'use client'

import { useState } from 'react'
import dynamic from 'next/dynamic'
import { Activity, ArrowDownRight, ArrowUpRight, ChartNoAxesCombined, ChevronRight, CircleHelp, Command, Crosshair, Database, Gauge, Gem, LayoutDashboard, LockKeyhole, Radio, RefreshCw, Scale, ShieldCheck, SlidersHorizontal, TriangleAlert, Zap } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert'
import { useMarket } from '@/hooks/use-market'
import { compact, formatPrice, type Bar } from '@/lib/market-types'
import { cn } from '@/lib/utils'
import { StatusDot } from './panel'
import { SignalPanel } from './signal-panel'
import { DerivativesPanel, IndicatorPanel, OrderBook, RiskSizer, SignalHistory } from './market-panels'
import { MethodologyDialog } from './methodology-dialog'

const PriceChart = dynamic(() => import('./price-chart').then(m => m.PriceChart), { ssr: false, loading: () => <div className="terminal-panel min-h-132"><div className="panel-heading">PRICE ACTION</div><div className="flex flex-1 items-center justify-center text-xs text-muted-foreground">Loading chart engine…</div></div> })
const SourcesPanel = dynamic(() => import('./sources-panel').then(m => m.SourcesPanel), { loading: () => <div className="p-8 text-sm text-muted-foreground">Loading market provenance…</div> })
type View = 'terminal' | 'signals' | 'sources' | 'risk'
const views = [{ id: 'terminal', label: 'Terminal', icon: LayoutDashboard }, { id: 'signals', label: 'Signal engine', icon: Crosshair }, { id: 'sources', label: 'Market data', icon: Database }, { id: 'risk', label: 'Risk calculator', icon: Scale }] as const

export function Terminal() {
  const [bar, setBar] = useState<Bar>('15m')
  const [view, setView] = useState<View>('terminal')
  const [methodology, setMethodology] = useState(false)
  const m = useMarket(bar)
  const { ticker, now } = m
  const change = ticker && Number(ticker.open24h) > 0 ? (Number(ticker.last) / Number(ticker.open24h) - 1) * 100 : null
  const positive = change !== null && change >= 0
  const seconds = now ? Math.floor((900_000 - now % 900_000) / 1000) : null
  const countdown = seconds === null ? '—' : `${String(Math.floor(seconds / 60)).padStart(2, '0')}:${String(seconds % 60).padStart(2, '0')}`
  const shownSetup = m.actionable ? m.analysis.setup : null
  const down = !m.loading && !m.fresh

  return <div className="terminal-app">
    <a href="#workspace" className="sr-only focus:not-sr-only focus:fixed focus:top-2 focus:left-20 focus:z-50 focus:rounded focus:bg-primary focus:p-3 focus:text-primary-foreground">Skip to terminal workspace</a>
    <header className="app-header"><a href="/" className="flex shrink-0 items-center gap-3" aria-label="Omniscient terminal home"><span className="brand-mark"><Gem className="size-5" strokeWidth={1.5} /></span><span><span className="block text-[14px] font-semibold tracking-[0.18em]">OMNISCIENT<span className="text-primary">.</span></span><span className="mt-1 block text-[8px] tracking-[0.22em] text-muted-foreground">PRECISION MARKET INTELLIGENCE</span></span></a><span className="ml-5 hidden h-6 border-l border-border lg:block" /><div className="ml-5 hidden items-center gap-2 lg:flex"><span className="text-[10px] text-muted-foreground">WORKSPACE</span><ChevronRight className="size-3 text-muted-foreground" /><span className="text-[10px]">Gold terminal</span></div><div className="ml-auto flex items-center gap-3 sm:gap-5"><Badge variant="outline" className="hidden h-6 gap-1.5 rounded border-border bg-positive/4 text-[9px] font-normal text-positive sm:inline-flex"><ShieldCheck className="size-3" />REAL DATA ONLY</Badge><div className="hidden text-right font-mono md:block"><div className="text-[11px] text-foreground">{now ? new Date(now).toISOString().slice(11, 19) : '--:--:--'} <span className="text-muted-foreground">UTC</span></div><div className="mt-1 text-[8px] text-muted-foreground">{now ? new Intl.DateTimeFormat('en-GB', { day: '2-digit', month: 'short', year: 'numeric', timeZone: 'UTC' }).format(now).toUpperCase() : 'SYNCING EXCHANGE'}</div></div><Button size="icon-sm" variant="ghost" aria-label="Refresh exchange connections" title="Refresh exchange connections" onClick={m.refresh} className="text-muted-foreground"><RefreshCw className="size-3.5!" /></Button><span className="hidden h-5 border-l border-border sm:block" /><span className="flex size-7 items-center justify-center rounded-md border border-primary/20 bg-primary/8 font-mono text-[10px] text-primary">AU</span></div></header>
    <div className="app-body"><aside className="icon-rail" aria-label="Workspace navigation"><div className="flex flex-col gap-3">{views.map(item => <Button key={item.id} variant="ghost" size="icon" onClick={() => setView(item.id)} aria-label={item.label} title={item.label} aria-current={view === item.id ? 'page' : undefined} className={cn('size-9 rounded-md', view === item.id ? 'bg-primary/10 text-primary' : 'text-muted-foreground hover:text-foreground')}><item.icon className="size-4!" /></Button>)}</div><div className="mt-auto flex flex-col gap-4"><span className="mx-auto h-8 border-l border-border" /><Button variant="ghost" size="icon" onClick={() => setMethodology(true)} aria-label="Read methodology and risk disclosures" className="text-muted-foreground"><CircleHelp className="size-4!" /></Button><span className="mx-auto mb-1 size-1.5 rounded-full bg-primary/70" /></div></aside>
    <div className="workspace-shell"><nav className="workspace-nav" aria-label="Terminal sections"><div className="flex min-w-0 items-stretch gap-5 overflow-x-auto sm:gap-7">{views.map(item => <button key={item.id} onClick={() => setView(item.id)} aria-current={view === item.id ? 'page' : undefined} className={cn('workspace-tab', view === item.id && 'active')}><item.icon className="size-3" />{item.label}{item.id === 'terminal' && <span className="ml-1 hidden rounded bg-primary/12 px-1.5 py-0.5 font-mono text-[8px] text-primary sm:inline">LIVE</span>}</button>)}</div><div className="ml-auto hidden shrink-0 items-center gap-2 pl-4 text-[9px] text-muted-foreground lg:flex"><LockKeyhole className="size-3 text-primary" />Closed-candle protection<Badge variant="outline" className="ml-2 h-4 rounded border-border px-1 text-[8px] text-muted-foreground">v15.0</Badge></div></nav>
    <main id="workspace" className="workspace-content">
      <div className="instrument-strip"><div className="flex shrink-0 items-center gap-3"><span className="gold-coin"><span className="text-[19px] font-semibold leading-none">Au</span><span className="mt-1 text-[7px] tracking-[0.15em]">GOLD</span></span><div><div className="flex items-center gap-2"><h1 className="text-lg font-semibold tracking-tight">XAU<span className="font-normal text-muted-foreground"> / </span>USDT</h1><span className="rounded border border-border px-1.5 py-0.5 text-[8px] text-muted-foreground">PERP</span></div><div className="mt-1 flex items-center gap-1.5 text-[9px] text-muted-foreground"><span className="grid grid-cols-2 gap-0.5" aria-hidden="true">{[0,1,2,3].map(i => <span key={i} className="size-1 bg-foreground/70" />)}</span>OKX<span className="mx-1 text-border">/</span>Gold perpetual futures</div></div></div><div className="price-block"><div className="font-mono text-[30px] leading-none font-medium tracking-[-0.05em]">{formatPrice(ticker?.last, 1)}</div><div className={cn('mt-2 flex items-center gap-1 text-[10px]', positive ? 'text-positive' : 'text-negative')}>{change !== null && (positive ? <ArrowUpRight className="size-3" /> : <ArrowDownRight className="size-3" />)}<span className="font-mono">{change === null ? '—' : `${positive ? '+' : ''}${change.toFixed(2)}%`}</span><span className="ml-1 text-muted-foreground">24h change</span></div></div><div className="ticker-stat"><span>24h high</span><b>{formatPrice(ticker?.high24h, 1)}</b></div><div className="ticker-stat"><span>24h low</span><b>{formatPrice(ticker?.low24h, 1)}</b></div><div className="ticker-stat"><span>24h volume <small>XAU</small></span><b>{compact(ticker?.volCcy24h)}</b></div><div className="ticker-stat hidden xl:flex"><span>Best bid / ask</span><b>{formatPrice(m.book?.bids[0]?.[0], 1)} <em>/</em> {formatPrice(m.book?.asks[0]?.[0], 1)}</b></div><div className="ml-auto shrink-0 text-right"><div className={cn('inline-flex items-center gap-1.5 rounded border px-2 py-1 text-[9px]', m.fresh ? 'border-positive/20 bg-positive/5 text-positive' : 'border-primary/20 bg-primary/5 text-primary')}><StatusDot live={m.fresh} />{m.fresh ? m.connected ? 'LIVE STREAM' : 'LIVE · REST' : m.loading ? 'CONNECTING' : 'DELAYED'}</div><div className="mt-2 font-mono text-[9px] text-muted-foreground">{m.quoteAge === null ? 'Synchronizing' : `${(m.quoteAge / 1000).toFixed(1)}s quote age`}</div></div></div>
      {down && <Alert className="mb-4 border-primary/20 bg-primary/5 text-primary"><TriangleAlert /><AlertTitle className="text-xs">Market data is not currently actionable</AlertTitle><AlertDescription className="text-[11px]">{m.error || 'Awaiting fresh quotes, order book and instrument verification.'} Historical values may remain visible. Entry levels are blocked; no fallback asset is used.</AlertDescription></Alert>}
      {view === 'terminal' && <><div className="section-intro"><div className="flex items-center gap-2"><span className="text-[11px] font-medium">Market overview</span><span className="text-[9px] text-muted-foreground">/</span><span className="text-[10px] text-muted-foreground">A clearer edge. A disciplined execution.</span></div><div className="flex items-center gap-2 text-[9px] text-muted-foreground"><span className="hidden sm:inline">NEXT 15M CLOSE</span><span className="font-mono text-primary">{countdown}</span><span className="mx-1 h-3 border-l border-border" /><Activity className="size-3 text-primary" /><span>5-factor engine</span></div></div><div className="primary-grid"><PriceChart candles={m.candles} bar={bar} onBarChange={setBar} setup={shownSetup} live={m.fresh} tick={Number(m.instrument?.tickSz)} error={m.chartError} /><SignalPanel market={m} onMethodology={() => setMethodology(true)} /></div><div className="secondary-grid"><IndicatorPanel market={m} /><OrderBook market={m} /><DerivativesPanel market={m} /></div><SignalHistory market={m} /></>}
      {view === 'signals' && <><div className="mb-5"><div className="eyebrow">CLOSED-CANDLE INTELLIGENCE</div><h2 className="mt-2 text-2xl font-medium tracking-tight">Confirmation before conviction.</h2><p className="mt-2 text-xs text-muted-foreground">Live quotes never rewrite a confirmed direction. A breached setup is invalidated, not instantly reversed.</p></div><div className="grid gap-4 lg:grid-cols-[1fr_340px]"><div className="flex flex-col gap-4"><IndicatorPanel market={m} /><SignalHistory market={m} /></div><SignalPanel market={m} onMethodology={() => setMethodology(true)} /></div></>}
      {view === 'sources' && <SourcesPanel market={m} />}
      {view === 'risk' && <><div className="mb-5"><div className="eyebrow">RISK BEFORE REWARD</div><h2 className="mt-2 text-2xl font-medium tracking-tight">Size the risk. Respect the market.</h2><p className="mt-2 text-xs text-muted-foreground">A planning tool based on verified contract sizes and the active setup. Not a trading account or order entry.</p></div><RiskSizer market={m} /><div className="mt-4 grid gap-4 md:grid-cols-2"><SignalPanel market={m} onMethodology={() => setMethodology(true)} /><DerivativesPanel market={m} /></div></>}
      <div className="workspace-disclaimer"><ShieldCheck className="size-3 shrink-0 text-primary" /><p>Designed for discipline, not certainty. No signal guarantees profit. Trade only with capital you can afford to lose.</p><button onClick={() => setMethodology(true)} className="ml-auto shrink-0 text-primary hover:underline">Methodology <span aria-hidden="true">↗</span></button></div>
    </main><footer className="status-footer"><div className="flex flex-wrap items-center gap-4"><span className="flex items-center gap-1.5"><StatusDot live={m.fresh} /><span className={m.fresh ? 'text-positive' : 'text-primary'}>{m.fresh ? 'MARKET FEED CONNECTED' : 'AWAITING VERIFIED FEED'}</span></span><span className="hidden sm:inline">OKX · XAU-USDT-SWAP</span><span className="hidden lg:inline">{m.connected ? 'WebSocket + REST recovery' : 'REST recovery · 3s polling'}</span></div><span className="hidden items-center gap-1.5 sm:flex"><ShieldCheck className="size-3" />No simulated data<span className="mx-2 text-border">|</span><span className="text-primary">OMNISCIENT v15</span></span></footer></div></div>
    <MethodologyDialog open={methodology} onOpenChange={setMethodology} tick={m.instrument?.tickSz} />
  </div>
}
